runtime: python39
entrypoint: gunicorn -k geventwebsocket.gunicorn.workers.GeventWebSocketWorker -w 1 --timeout 120 main:app
instance_class: F4_HIGHMEM


runtime_config:
  python_version: 3.9

includes:
- requirements.txt

automatic_scaling:
  min_instances: 1
  max_instances: 30
  target_cpu_utilization: 0.7
  target_throughput_utilization: 0.7
  max_concurrent_requests: 100

env_variables:
  BUCKET_NAME: "triple-odyssey-435000-i0.appspot.com"
  SECRET_KEY: "your_secret_key_here"
  GAE_MAX_CONCURRENT_REQUESTS: "100"
  GAE_USE_SOCKETS_HTTPLIB : 'true'

network:
  session_affinity: true

handlers:
- url: /static
  static_dir: static

- url: /socket.io/
  script: auto
  secure: always

- url: /.*
  script: auto

inbound_services:
- warmup

readiness_check:
  app_start_timeout_sec: 300